const S3_PREFIX_URL = 'https://s3-ap-southeast-2.amazonaws.com/dius-site'
const IMGIX_PREFIX_URL = 'http://dius.imgix.net'
const S3_BUCKET = 'dius-site'
const S3_IMAGES_PREFIX = 'images'
const S3_PDF_PREFIX = 'pdf'
const ACCEPTED_IMAGES = '.png,.jpg,.jpeg,.gif'
const ACCEPTED_PDF = '.pdf'
